### ISSUE TITLE
Imported ServiceRecords get orphaned if the Client Registry missed the Delete event

### ISSUE THREAD

**Issue by jamiemonserrate** [vmware-tanzu/cross-cluster-connectivity#30]
## Environment:
 - Cross-cluster connectivity version:
 - Kubernetes version: (use `kubectl version`):
 - Cloud provider or hardware configuration:

**Comment by rosenhouse** [comment]
Discussed a design where the registry-client will add annotations to imported ServiceRecords so that it is possible to associate them with a unique service from a known registry-server.  Then, on restart of a registry-client, or on re-connect to a restarted registry-server, the client will download a complete snapshot of services from that registry and can then prune any local ServiceRecords which aren't represented in that snapshot.
