### ISSUE TITLE
Reliability feature: admin of cluster A shouldn't be able to impact availability of our service on clusters B, C, D...

### ISSUE THREAD

**Issue by rosenhouse** [vmware-tanzu/cross-cluster-connectivity#68]
Overall feature: an accidental or malicious action by someone with cluster-admin access on 1 cluster shouldn't impact the availability of the cross-cluster DNS service on other clusters.

This might include (but not limited to):
- mucking with the `projectcontour` namespace on a workload cluster
- mucking with the `capi-dns` namespace on a workload cluster
- breaking my cluster

where "mucking with" might include edit/delete resources inside the namespace, or just deleting the namespace entirely.

A related (maybe separate???) set of features is that a cluster ought to be able to participate in the cross-cluster DNS system as a "client only" (no ingress) or "service only" (no DNS resolver).

**Comment by tylerschultz** [comment]
## As it stands today before doing work on this issue: 

If a cluster were to rename the `projectcontour` namespace on a workload cluster, the `GatewayDNS` resource on the management cluster would no longer match the cluster, and the EndpointSlices associated with the `GatewayDNS` resource would be deleted from all workload clusters. 

When a `Cluster` does not have the `xcc-dns`, formerly `capi-dns`, namespace (through edit or delete on the wc), the `GatewayDNSController` will ignore the `Cluster` and not attempt to CRUD `EndopintSlices` on that cluster. 

The last scenario where a cluster can participate as a "client only" or "service only" seemingly should work now, but perhaps should be validated.

## Work still to be done:

I propose the following:

Suppose the scenario where `Cluster` A has `Services` that match a `GatewayDNS` record, and had `EndpointSlices` representing these `Services` on `Cluster` B. If `Cluster` A were to become unreachable, then the corresponding `EndpointSlices` on `Cluster` B would be deleted. The inability of the `GatewayDNSController` to reach `Cluster` A should not delete the `EndpointSlices` from `Cluster` B because `Cluster` B may still have connectivity to `Cluster` A. EndpointSlices should not be deleted from Clusters when a providing Cluster is not reachable from the `GatewayDNSController`.
