### ISSUE TITLE
Support FQDN EndpointSlices

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/cross-cluster-connectivity#96]
## Description
I have a specific scenario where I need to connect from a cluster to a remote cluster as if it was the local cluster, for this I would rather use the FQDN for the remote service than a IPv4.

## Additional Context
I'm evaluating the suitability of cross-cluster-connectivity so that I can use on a local cluster services that are living on remote clusters. Since the xxc-dns-controller is running on the management cluster and using two different infras would not work, I have hacked a scenario where I only have installed the xcc-dns-server and created a manually EndpointSlice to the remote service/cluster. There's a working PoC here: https://github.com/jorgemoralespou/xxc-demo

What I'm looking for is an lightweight alternative to Tanzu Service Mesh to the scenarios where as a developer I want to connect the application I'm working in my local cluster to the services running on a remote/shared cluster so that I can lower the resource consumption on my local machine, or that I can use services that wouldn't run locally.

Obviously as it is right now, the PoC doesn't provide much benefit, as I could have connected directly to my remote service via the ingress specified there. I'm looking if this is a use case that in the future xxc could solve.

**Comment by rosenhouse** [comment]
Thanks for reporting this!

Note for anyone who wants to pick this up: My naive thought here is that `dns-server` would watch for `addressType: FQDN` in the `EndpointSlice` ([example](https://github.com/jorgemoralespou/xxc-demo/blob/e3df1e196f9cd120ef65b04cf74f4ca57a522079/cluster-local/EndpointSlice.yaml#L9)) and just return a `CNAME` record in this case, rather than an `A` record.
